# Generated by Django 4.0 on 2022-01-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_ID', models.IntegerField()),
                ('fullName', models.CharField(max_length=250)),
                ('passport', models.CharField(max_length=50)),
                ('birthDate', models.DateTimeField(null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('analysis_date', models.DateTimeField(null=True)),
                ('result', models.CharField(choices=[('negative', 'Negative'), ('positive', 'Positive')], max_length=50)),
                ('result_date', models.DateTimeField(null=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
        ),
    ]
